[program:laravel-reverb]
process_name=%(program_name)s
command=php /var/www/student06/backend/artisan reverb:start --host=0.0.0.0 --port=8080 --no-interaction
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=student06
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/student06/backend/storage/logs/reverb.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5
stopwaitsecs=10
