[program:laravel-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/student06/backend/artisan queue:work --sleep=3 --tries=3 --max-time=3600
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=student06
numprocs=2
redirect_stderr=true
stdout_logfile=/var/www/student06/backend/storage/logs/worker.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5
stopwaitsecs=3600
